import '@/components/Accordions/Accordions.makeswift'
import '@/components/Marquee/Marquee.makeswift'
import '@/components/Tabs/Tabs.makeswift'
import '@/components/ActionGraph/ActionGraph.makeswift'
import '@/components/ActionTime/ActionTime.makeswift'
